# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 03:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='picture',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='picture',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='picture',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='picture',
            name='width',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='picture',
            name='pic',
            field=models.ImageField(height_field='height', upload_to=b'', width_field='width'),
        ),
    ]
